name: Pipeline
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        blender: [latest, 3.6lts, 3.3lts, 2.93lts, 2.83lts]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Blender
      run: |
        sudo apt-get install -y libglu1-mesa
        sudo snap install blender --channel=${{ matrix.blender }}/stable --classic
    - name: Run Tests
      run: |
        python -m pip install -e .[test]
        python -m pytest
  build_publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
