name: Pipeline
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        blender: [latest, '4.2', '3.6']
        os: [ubuntu-latest, windows-latest]
        pyversion: ['3.8']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.pyversion }}
    - uses: Moguri/setup-blender@v1
      id: setup-blender
      with:
        blender-version: ${{ matrix.blender }}
    - name: Run Tests
      run: |
        blender --version
        uv sync
        uv run pytest
  build_publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
    - name: Build package
      run: |
        uv sync
        uv build
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
