name: Pipeline
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        blender: [latest, '3.6']
        os: [ubuntu-latest, windows-latest]
        pyversion: ['3.8']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyversion }}
        cache: pip
    - uses: Moguri/setup-blender@v1
      id: setup-blender
      with:
        blender-version: ${{ matrix.blender }}
    - name: Run Tests
      run: |
        blender --version
        python -m pip install -e .[test]
        python -m pytest
  build_publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
